#app
server:
    port: 8080

#spring
spring:
  devtools:
    restart:
      enabled: true

  # DATABASE CONFIG
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-came: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.168.0.147:3306/stock?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: pmo#04052017P
      #数据库密码加密
      #java -cp druid-1.1.2.jar com.alibaba.druid.filter.config.ConfigTools pmo#04052017P
      #privateKey: 
      #public-key:
      #password: 
      #下面为连接池的补充设置，应用到上面所有数据源中
      #初始化连接数量，最大最小连接数
      initial-size: 2
      max-active: 5
      min-idle: 3
      #获取连接等待超时的时间
      max-wait: 600000
      #超过时间限制是否回收
      remove-abandoned: true
      #超过时间限制多长
      remove-abandoned-timeout: 180
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 600000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1 FROM DUAL
      #申请连接的时候检测
      test-while-idle: true
      #申请连接时执行validationQuery检测连接是否有效，配置为true会降低性能
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效，配置为true会降低性能
      test-on-return: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 50
      #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
      #监控统计用的filter:stat 日志用的filter:log4j 防御SQL注入的filter:wall
      filters: stat,wall,log4j,config
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=false;config.decrypt.key=${spring.datasource.druid.public-key}
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true #是否启用StatFilter默认值true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
        session-stat-max-count:
        principal-session-name:
        principal-cookie-name:
        profile-enable:
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true #是否启用StatViewServlet默认值true
        url-pattern: '/druid/*'
        reset-enable:
        login-username: admin
        login-password: admin
        allow:
        deny:

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  typeAliasesPackage: com.lean.**.entity
  global-config:
    id-type: 0
    field-strategy: 2
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#logging
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  file: /app/logs/lean-api.log